import { SocialPost } from "@/lib/types";

export const samplePosts: SocialPost[] = [
  {
    id: "demo-1",
    date: "2026-05-29",
    accountType: "business",
    platform: "Instagram",
    status: "drafted",
    category: "client-work",
    campaign: "M&M Cleaning Launch",
    city: "Renton",
    mediaReferences: ["m-and-m-hero-reel.mov", "pink-blue-brand-board.png"],
    crossPostedTo: ["Facebook", "Google Business Profile"],
    tags: ["cleaning", "renton", "launch"],
    caption:
      "A cleaner home really does make the whole week feel lighter. We built M&M Cleaning Service to be easy to reach, careful in the details, and dependable from the first visit on.",
    notes: "Use with hero reel and logo reveal. Keep CTA focused on quote requests.",
    createdAt: "2026-05-29T08:00:00.000Z",
    updatedAt: "2026-05-29T08:00:00.000Z",
  },
  {
    id: "demo-2",
    date: "2026-05-28",
    accountType: "personal",
    platform: "LinkedIn",
    status: "posted",
    category: "local-growth",
    campaign: "Seattle Trip Reflection",
    city: "Seattle",
    mediaReferences: ["seattle-waterfront-clip.mp4"],
    crossPostedTo: [],
    tags: ["seattle", "founder", "web-development"],
    caption:
      "One thing I keep coming back to as I grow CSolutions is how much trust still matters. Local proof, clear systems, and thoughtful follow-through do more work than any flashy pitch ever will.",
    notes: "Strong personal/founder post. Reuse tone for local credibility posts later.",
    createdAt: "2026-05-28T15:10:00.000Z",
    updatedAt: "2026-05-28T15:10:00.000Z",
  },
  {
    id: "demo-3",
    date: "2026-05-27",
    accountType: "business",
    platform: "Google Business Profile",
    status: "drafted",
    category: "promotion",
    campaign: "Summer Booking Push",
    city: "Boston",
    mediaReferences: ["luxury-gifts-mobile-screenshot.png"],
    crossPostedTo: ["Instagram"],
    tags: ["summer", "promotion", "booking"],
    caption:
      "Summer moves fast, and so do content deadlines. If your business needs a site that looks polished and actually helps people reach out, we can build that with you.",
    notes: "Business-development post. Could cross-post to Facebook if shortened.",
    createdAt: "2026-05-27T12:30:00.000Z",
    updatedAt: "2026-05-27T12:30:00.000Z",
  },
  {
    id: "demo-4",
    date: "2026-05-26",
    accountType: "business",
    platform: "TikTok",
    status: "reposted",
    category: "video-script",
    campaign: "Template Showcase",
    city: "Boston",
    mediaReferences: ["barber-template-tour.mp4"],
    crossPostedTo: ["Instagram", "Facebook"],
    tags: ["template", "video", "showcase"],
    caption:
      "Quick walkthrough of a premium site template built for small businesses that want to look established online without feeling generic.",
    notes: "Keep as short-form script lead. Maybe expand into YouTube short later.",
    createdAt: "2026-05-26T17:20:00.000Z",
    updatedAt: "2026-05-26T17:20:00.000Z",
  },
  {
    id: "demo-5",
    date: "2026-05-24",
    accountType: "personal",
    platform: "Facebook",
    status: "archived",
    category: "community",
    campaign: "Local Scenic Photos",
    city: "Boston",
    mediaReferences: ["charles-river-evening.jpg"],
    crossPostedTo: ["Instagram"],
    tags: ["local", "community", "photo"],
    caption:
      "I’ve been collecting more local photos lately. Part of it is just because they’re beautiful, but part of it is also wanting the work I do online to feel grounded in the places I actually spend time in.",
    notes: "Archive example. Good tone reference for personal/local trust content.",
    createdAt: "2026-05-24T20:00:00.000Z",
    updatedAt: "2026-05-24T20:00:00.000Z",
  },
];
